package com.sample

import static com.sample.FamilyMovieMain.*;
import java.util.ArrayList;

declare Activity
	question: String @key
	respond: String
end

declare permissionToNextWindow

end

rule "Init"
	when
	then
		String questionContent = "What type of movie do they feel like watching?";
		ArrayList<String> options = new ArrayList<>();
		options.add("Take us on an adventure!");
		options.add("We love to laugh!");
		options.add("We're big sports fans!");
		options.add("We have a soft spot for animation!");
		options.add("We like to sign and dance!");
		options.add("We're animal lovers!");
		options.add("We want to be wowed!");
		
		Activity a = new Activity(questionContent);
		ArrayList<Integer> responds = multiplicityQuestion(a.getQuestion(), options);
		for(int i=0; i<responds.size(); i++){
			a = new Activity(questionContent);
			a.setRespond(options.get(	responds.get(i)	));
			insert(a);
		}	
end







