//created on: 2019-12-08
package com.sample

//list any import classes here.
import static com.sample.FamilyMovieMain.*;
import java.util.ArrayList;


declare Activity
	question: String @key
	respond: String
end


rule "We like to sign and dance!"
	when 
		Activity(question == "What type of movie do they feel like watching?", respond=="We like to sign and dance!")
	then
		respondBoard("Wybra³eœ We like to sign and dance!");
end

