//created on: 2019-12-08
package com.sample

//list any import classes here.
import static com.sample.FamilyMovieMain.*;
import java.util.ArrayList;


declare Activity
	question: String @key
	respond: String
end

rule "Take us on an adventure!"
	when 
		Activity(question == "What type of movie do they feel like watching?", respond=="Take us on an adventure!")
	then
		respondBoard("Wybra³eœ Take us on an adventure!");
end
